name: Build & Push Devcontainer Image

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        run: |
          # Convert GitHub username to lowercase
          USERNAME=$(echo "${GITHUB_REPOSITORY_OWNER}" | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME=ghcr.io/$USERNAME/glimpse2-dev:latest
          echo "Building Docker image $IMAGE_NAME"
          docker build -t $IMAGE_NAME -f .devcontainer/Dockerfile .
          echo "Pushing Docker image $IMAGE_NAME"
          docker push $IMAGE_NAME
