name: Build & Deploy Docs

on:
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/glimpse2-dev:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build project & generate docs
        run: cmake -S . -B build -DTEST=OFF -DDOXY=ON && cmake --build build

      - name: Create .nojekyll
        run: touch build/docs/html/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/docs/html
          publish_branch: gh-pages
